### ISSUE TITLE
PyPI, Github actions

### ISSUE THREAD

**Issue by janbuchar** [skaut/skautis-py#2]
Bylo by fajn, kdyby šlo balíček nainstalovat z pypi. To by asi snadno šlo spouštět pomocí github actions, stejně jako ten autoupdate skript (actions umí nightly build).

Mám to udělat?

**Comment by kulikjak** [comment]
Aha, nevím proč jsem si myslel, že to už na pypi je. Jsem určitě pro, jen teď koukám, že je tu problém, který by chtěl vyřešit před tím: Autoupdate script, který každou noc regeneruje tuto knihovnu, se zdá se rozbil a vyrábí nové verze i když se nic nezmění.

Jsem teď na dovolené, takže jsem ho prozatím jen vypnul, nicméně až se příští týden vrátím, tak to opravím, revertnu všechny zbytečné verze a potom to bude ready pro pypi.

**Comment by janbuchar** [comment]
No, a nebylo by lepší rovnou udělat ten autoupdate přes actions?

**Comment by kulikjak** [comment]
No to je asi fakt. Mně to teď běhá na raspberry pi v cronu doma na stole, což není úplně ideální - kdyby to celé dělaly GitHub actions, tak je to minimálně lépe udržovatelné a průhledné.

Sám nemám s actions mnoho zkušeností, nicméně PR určitě moc rád uvítám!
