### ISSUE TITLE
Použití s Flask factory pattern

### ISSUE THREAD

**Issue by janpeterka** [skaut/skautis-py#4]
Šlo by přidat kód, aby se dalo používat s factory pattern?

Představuju si něco jako 

```python
# __init__.py
skautis = SkautisApi(test=True)  # aby byla importovatelná

def create_app():
    skautis.set_defaults(app.config['SKAUTIS_APPID'])

```

Případně vymakanější, ale běžná konvence:

```python
# __init__.py
skautis = SkautisApi(test=True) 

def create_app():
    skautis.init_app(app)

```

Kód klidně nahodím do PR, ale nevím, jak je to s tím automatickým generováním.

**Comment by kulikjak** [comment]
Přiznám se, že nejsem uplně _pattern guy_, takže je možné, že mi něco uniká, ale přijde mi, že i pro factory pattern by to mělo fungovat například takto:

```python
skautis = SkautisApi(None, test=True)

def create_app():
    skautis._appId = app.config['SKAUTIS_APPID']
```

Není to pravda úplně nejhezčí, ale fugovat to bude, protože `appId` je potřeba jen pro `get_login_url()` a `get_logout_url()` a dokud se nevolají, tak nemusí existovat.

**Comment by janpeterka** [comment]
jo, to by určitě fungovat mělo. jenom to není moc elegantní, no :D

klidně hodím návrh kódu s tím `init_app`, což je běžná konvence..

**Comment by kulikjak** [comment]
Omlouvám se za dlouhou neaktivitu, polepším se.

K PR jsem dopsal pár poznámek, proč by takto nefungovalo. Nicméně ani tak se mi toto moc mergeovat nechce.

1. Osobně jsem zastánce toho, že by měla existovat právě jedna cesta jak knihovnu inicializovat - kor když je takto jednoduchá. Takto bychom měli dvě různé cesty pro nastavení jedné nebo dvou hodnot...
2. Implementace `init_app()` je dělaná přímo pro Flask, což jen jeden z mnoha web frameworků a přidávat kód pro konkrétní jednu další python knihovnu (se kterou tato navíc nemá nic společného) moc nechci - nehledě na to, že se tato knihovna dá použít se spoustou aplikací, které vůbec nesouvisí s webem. Myslím si, že to sem úplně nepatří.

Nicméně mám návrh jak to vyřešit pěkně snad ke spokojenosti ;). Podle mě jednodušší je wrapnout celou knihovnu a přidat si `init_app()` dle potřeb třeba následujícím způsobem:

```python
class SkautisApi:

    def init_app(self, app):
        appId = app.config.setdefault("SKAUTIS_APPID", None)
        test = app.config.setdefault("SKAUTIS_TEST", False)
        from skautis import SkautisApi as _SkautisApi
        self._skautis = _SkautisApi(appId, test)

    def __getattr__(self, name):
        return getattr(self._skautis, name)
```

Takhle se dokonce pořád jmenuje stejně a tedy dá importovat pod stejným jménem :). Pokud je třeba, dá se tam přidat i check, že se `init_app` zavolalo:

```python

    def __getattr__(self, name):
        if not self._skautis:
            raise RuntimeError("init_app was never called.")
        return getattr(self._skautis, name)
```

Když už tu máme ten Flask example, tak já to k němu mohu přidat, aby to bylo někde pěkně vidět i v budoucnosti. Teoreticky by se dala vytvořit druhá knihovna (něco jako **skautis-py-flask**), která by byla přímo šitá pro Flask a tam by se toto všechno určitě hodilo. Jen nevím, jestli by ji vůbec někdo použil...

---
Nakonec pod čarou: všechno co je ve složce `skautis` se generuje automaticky (vyrábí to [skautis_api_gen.py](https://github.com/skaut/skautis-py/blob/master/skautis_api_gen.py)), takže takto by se to hned v první půlnoci přepsalo zpět. Změny se kdyžtak musí dát do [skautis_api.mustache](https://github.com/skaut/skautis-py/blob/master/skautis_api.mustache).

**Comment by janpeterka** [comment]
Díky za komentáře a návrhy!

To co píšeš mi dává smysl - jak to, že nechceš implementovat něco takhle jednoúčelového. Když bude tohle řešení v examplu, tak mi to přijde úplně skvělý (případně možná jako nový example, ať je jeden simple a tenhle rozšířený).

**Comment by kulikjak** [comment]
Super, tak já to v příštích pár dnech do těch examples přidám. Ten původní tam asi fakt nechám - ne každý používá `init_app` factory pattern a příklady tam mohou být oba ;).

**Comment by janpeterka** [comment]
Díky moc :)

**Comment by kulikjak** [comment]
@janmpeterka tak je to tam i s novým readme.
